/**
 * Crypto Keys
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CryptoKeys);
  }
}(this, function(expect, CryptoKeys) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CryptoKeys.JsonWebKey();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JsonWebKey', function() {
    it('should create an instance of JsonWebKey', function() {
      // uncomment below and update the code to test JsonWebKey
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be.a(CryptoKeys.JsonWebKey);
    });

    it('should have the property d (base name: "d")', function() {
      // uncomment below and update the code to test the property d
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property e (base name: "e")', function() {
      // uncomment below and update the code to test the property e
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property crv (base name: "crv")', function() {
      // uncomment below and update the code to test the property crv
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property kid (base name: "kid")', function() {
      // uncomment below and update the code to test the property kid
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property k (base name: "k")', function() {
      // uncomment below and update the code to test the property k
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property dp (base name: "dp")', function() {
      // uncomment below and update the code to test the property dp
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property dq (base name: "dq")', function() {
      // uncomment below and update the code to test the property dq
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property n (base name: "n")', function() {
      // uncomment below and update the code to test the property n
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property p (base name: "p")', function() {
      // uncomment below and update the code to test the property p
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property kty (base name: "kty")', function() {
      // uncomment below and update the code to test the property kty
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property q (base name: "q")', function() {
      // uncomment below and update the code to test the property q
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property t (base name: "t")', function() {
      // uncomment below and update the code to test the property t
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property keyOps (base name: "key_ops")', function() {
      // uncomment below and update the code to test the property keyOps
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property qi (base name: "qi")', function() {
      // uncomment below and update the code to test the property qi
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property x (base name: "x")', function() {
      // uncomment below and update the code to test the property x
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

    it('should have the property y (base name: "y")', function() {
      // uncomment below and update the code to test the property y
      //var instane = new CryptoKeys.JsonWebKey();
      //expect(instance).to.be();
    });

  });

}));
