/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Sphereon.SDK.Crypto.Keys.Client;
using Sphereon.SDK.Crypto.Keys.Api;
using Sphereon.SDK.Crypto.Keys.Model;

namespace Sphereon.SDK.Crypto.Keys.Test
{
    /// <summary>
    ///  Class for testing CertApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CertApiTests
    {
        private CertApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CertApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CertApi
            //Assert.IsInstanceOfType(typeof(CertApi), instance, "instance is a CertApi");
        }

        
        /// <summary>
        /// Test CreateCert
        /// </summary>
        [Test]
        public void CreateCertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string config = null;
            //CreateCertificateRequest certificateRequest = null;
            //var response = instance.CreateCert(config, certificateRequest);
            //Assert.IsInstanceOf<CreateCertificateResponse> (response, "response is CreateCertificateResponse");
        }
        
        /// <summary>
        /// Test DeleteCert
        /// </summary>
        [Test]
        public void DeleteCertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string config = null;
            //string name = null;
            //var response = instance.DeleteCert(config, name);
            //Assert.IsInstanceOf<DeletedCertificateBundleResponse> (response, "response is DeletedCertificateBundleResponse");
        }
        
        /// <summary>
        /// Test GetCert
        /// </summary>
        [Test]
        public void GetCertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string config = null;
            //string name = null;
            //string version = null;
            //var response = instance.GetCert(config, name, version);
            //Assert.IsInstanceOf<CertificateBundleResponse> (response, "response is CertificateBundleResponse");
        }
        
        /// <summary>
        /// Test ImportCert
        /// </summary>
        [Test]
        public void ImportCertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string config = null;
            //ImportCertificateRequest request = null;
            //var response = instance.ImportCert(config, request);
            //Assert.IsInstanceOf<CreateCertificateResponse> (response, "response is CreateCertificateResponse");
        }
        
        /// <summary>
        /// Test ListCerts
        /// </summary>
        [Test]
        public void ListCertsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string config = null;
            //var response = instance.ListCerts(config);
            //Assert.IsInstanceOf<CertificateMetadataListResponse> (response, "response is CertificateMetadataListResponse");
        }
        
    }

}
