/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Crypto.Keys.Api;
using Sphereon.SDK.Crypto.Keys.Model;
using Sphereon.SDK.Crypto.Keys.Client;
using System.Reflection;

namespace Sphereon.SDK.Crypto.Keys.Test
{
    /// <summary>
    ///  Class for testing Attributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AttributesTests
    {
        // TODO uncomment below to declare an instance variable for Attributes
        //private Attributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Attributes
            //instance = new Attributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Attributes
        /// </summary>
        [Test]
        public void AttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Attributes
            //Assert.IsInstanceOfType<Attributes> (instance, "variable 'instance' is a Attributes");
        }

        /// <summary>
        /// Test the property 'NotBeforeTime'
        /// </summary>
        [Test]
        public void NotBeforeTimeTest()
        {
            // TODO unit test for the property 'NotBeforeTime'
        }
        /// <summary>
        /// Test the property 'UpdatedTime'
        /// </summary>
        [Test]
        public void UpdatedTimeTest()
        {
            // TODO unit test for the property 'UpdatedTime'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Test]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

    }

}
