/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Crypto.Keys.Api;
using Sphereon.SDK.Crypto.Keys.Model;
using Sphereon.SDK.Crypto.Keys.Client;
using System.Reflection;

namespace Sphereon.SDK.Crypto.Keys.Test
{
    /// <summary>
    ///  Class for testing CertificateParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificateParametersTests
    {
        // TODO uncomment below to declare an instance variable for CertificateParameters
        //private CertificateParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificateParameters
            //instance = new CertificateParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificateParameters
        /// </summary>
        [Test]
        public void CertificateParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificateParameters
            //Assert.IsInstanceOfType<CertificateParameters> (instance, "variable 'instance' is a CertificateParameters");
        }

        /// <summary>
        /// Test the property 'Csr'
        /// </summary>
        [Test]
        public void CsrTest()
        {
            // TODO unit test for the property 'Csr'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'CertificateId'
        /// </summary>
        [Test]
        public void CertificateIdTest()
        {
            // TODO unit test for the property 'CertificateId'
        }
        /// <summary>
        /// Test the property 'StatusDetails'
        /// </summary>
        [Test]
        public void StatusDetailsTest()
        {
            // TODO unit test for the property 'StatusDetails'
        }
        /// <summary>
        /// Test the property 'IssuerParameters'
        /// </summary>
        [Test]
        public void IssuerParametersTest()
        {
            // TODO unit test for the property 'IssuerParameters'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Test]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

    }

}
