/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Crypto.Keys.Api;
using Sphereon.SDK.Crypto.Keys.Model;
using Sphereon.SDK.Crypto.Keys.Client;
using System.Reflection;

namespace Sphereon.SDK.Crypto.Keys.Test
{
    /// <summary>
    ///  Class for testing CertificatePolicy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CertificatePolicyTests
    {
        // TODO uncomment below to declare an instance variable for CertificatePolicy
        //private CertificatePolicy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CertificatePolicy
            //instance = new CertificatePolicy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatePolicy
        /// </summary>
        [Test]
        public void CertificatePolicyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CertificatePolicy
            //Assert.IsInstanceOfType<CertificatePolicy> (instance, "variable 'instance' is a CertificatePolicy");
        }

        /// <summary>
        /// Test the property 'LifetimeActions'
        /// </summary>
        [Test]
        public void LifetimeActionsTest()
        {
            // TODO unit test for the property 'LifetimeActions'
        }
        /// <summary>
        /// Test the property 'KeyProperties'
        /// </summary>
        [Test]
        public void KeyPropertiesTest()
        {
            // TODO unit test for the property 'KeyProperties'
        }
        /// <summary>
        /// Test the property 'X509Properties'
        /// </summary>
        [Test]
        public void X509PropertiesTest()
        {
            // TODO unit test for the property 'X509Properties'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Test]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'SecretProperties'
        /// </summary>
        [Test]
        public void SecretPropertiesTest()
        {
            // TODO unit test for the property 'SecretProperties'
        }

    }

}
