/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Crypto.Keys.Api;
using Sphereon.SDK.Crypto.Keys.Model;
using Sphereon.SDK.Crypto.Keys.Client;
using System.Reflection;

namespace Sphereon.SDK.Crypto.Keys.Test
{
    /// <summary>
    ///  Class for testing X509Properties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class X509PropertiesTests
    {
        // TODO uncomment below to declare an instance variable for X509Properties
        //private X509Properties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of X509Properties
            //instance = new X509Properties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of X509Properties
        /// </summary>
        [Test]
        public void X509PropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" X509Properties
            //Assert.IsInstanceOfType<X509Properties> (instance, "variable 'instance' is a X509Properties");
        }

        /// <summary>
        /// Test the property 'EnhancedKeyUsage'
        /// </summary>
        [Test]
        public void EnhancedKeyUsageTest()
        {
            // TODO unit test for the property 'EnhancedKeyUsage'
        }
        /// <summary>
        /// Test the property 'KeyUsage'
        /// </summary>
        [Test]
        public void KeyUsageTest()
        {
            // TODO unit test for the property 'KeyUsage'
        }
        /// <summary>
        /// Test the property 'ValidityMonths'
        /// </summary>
        [Test]
        public void ValidityMonthsTest()
        {
            // TODO unit test for the property 'ValidityMonths'
        }
        /// <summary>
        /// Test the property 'Sans'
        /// </summary>
        [Test]
        public void SansTest()
        {
            // TODO unit test for the property 'Sans'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

    }

}
