/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Crypto.Keys.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Crypto.Keys.Model
{
    /// <summary>
    /// CertificateParameters
    /// </summary>
    [DataContract]
    public partial class CertificateParameters :  IEquatable<CertificateParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateParameters" /> class.
        /// </summary>
        /// <param name="Csr">Csr.</param>
        /// <param name="RequestId">RequestId.</param>
        /// <param name="CertificateId">CertificateId.</param>
        /// <param name="StatusDetails">StatusDetails.</param>
        /// <param name="IssuerParameters">IssuerParameters.</param>
        /// <param name="Status">Status.</param>
        /// <param name="Target">Target.</param>
        public CertificateParameters(string Csr = default(string), string RequestId = default(string), string CertificateId = default(string), string StatusDetails = default(string), IssuerParameters IssuerParameters = default(IssuerParameters), string Status = default(string), string Target = default(string))
        {
            this.Csr = Csr;
            this.RequestId = RequestId;
            this.CertificateId = CertificateId;
            this.StatusDetails = StatusDetails;
            this.IssuerParameters = IssuerParameters;
            this.Status = Status;
            this.Target = Target;
        }
        
        /// <summary>
        /// Gets or Sets Csr
        /// </summary>
        [DataMember(Name="csr", EmitDefaultValue=false)]
        public string Csr { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [DataMember(Name="requestId", EmitDefaultValue=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or Sets CertificateId
        /// </summary>
        [DataMember(Name="certificateId", EmitDefaultValue=false)]
        public string CertificateId { get; set; }

        /// <summary>
        /// Gets or Sets StatusDetails
        /// </summary>
        [DataMember(Name="statusDetails", EmitDefaultValue=false)]
        public string StatusDetails { get; set; }

        /// <summary>
        /// Gets or Sets IssuerParameters
        /// </summary>
        [DataMember(Name="issuerParameters", EmitDefaultValue=false)]
        public IssuerParameters IssuerParameters { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        [DataMember(Name="target", EmitDefaultValue=false)]
        public string Target { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CertificateParameters {\n");
            sb.Append("  Csr: ").Append(Csr).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  CertificateId: ").Append(CertificateId).Append("\n");
            sb.Append("  StatusDetails: ").Append(StatusDetails).Append("\n");
            sb.Append("  IssuerParameters: ").Append(IssuerParameters).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CertificateParameters);
        }

        /// <summary>
        /// Returns true if CertificateParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of CertificateParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CertificateParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Csr == other.Csr ||
                    this.Csr != null &&
                    this.Csr.Equals(other.Csr)
                ) && 
                (
                    this.RequestId == other.RequestId ||
                    this.RequestId != null &&
                    this.RequestId.Equals(other.RequestId)
                ) && 
                (
                    this.CertificateId == other.CertificateId ||
                    this.CertificateId != null &&
                    this.CertificateId.Equals(other.CertificateId)
                ) && 
                (
                    this.StatusDetails == other.StatusDetails ||
                    this.StatusDetails != null &&
                    this.StatusDetails.Equals(other.StatusDetails)
                ) && 
                (
                    this.IssuerParameters == other.IssuerParameters ||
                    this.IssuerParameters != null &&
                    this.IssuerParameters.Equals(other.IssuerParameters)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Target == other.Target ||
                    this.Target != null &&
                    this.Target.Equals(other.Target)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Csr != null)
                    hash = hash * 59 + this.Csr.GetHashCode();
                if (this.RequestId != null)
                    hash = hash * 59 + this.RequestId.GetHashCode();
                if (this.CertificateId != null)
                    hash = hash * 59 + this.CertificateId.GetHashCode();
                if (this.StatusDetails != null)
                    hash = hash * 59 + this.StatusDetails.GetHashCode();
                if (this.IssuerParameters != null)
                    hash = hash * 59 + this.IssuerParameters.GetHashCode();
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.Target != null)
                    hash = hash * 59 + this.Target.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
