/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Crypto.Keys.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Crypto.Keys.Model
{
    /// <summary>
    /// Key Metadata
    /// </summary>
    [DataContract]
    public partial class KeyMetadata :  IEquatable<KeyMetadata>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyMetadata" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KeyMetadata() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyMetadata" /> class.
        /// </summary>
        /// <param name="BackendMetadata">StorageType metadata. This is the place where additional metadata return from the backend is stored.</param>
        /// <param name="ApplicationMetadata">Application metadata. This is the place where you can store your own tags.</param>
        /// <param name="Managed">True if the key is backing a certificate.</param>
        /// <param name="Attributes">The attributes.</param>
        public KeyMetadata(Dictionary<string, string> BackendMetadata = default(Dictionary<string, string>), Dictionary<string, string> ApplicationMetadata = default(Dictionary<string, string>), bool? Managed = default(bool?), Attributes Attributes = default(Attributes))
        {
            this.BackendMetadata = BackendMetadata;
            this.ApplicationMetadata = ApplicationMetadata;
            this.Managed = Managed;
            this.Attributes = Attributes;
        }
        
        /// <summary>
        /// StorageType metadata. This is the place where additional metadata return from the backend is stored
        /// </summary>
        /// <value>StorageType metadata. This is the place where additional metadata return from the backend is stored</value>
        [DataMember(Name="backendMetadata", EmitDefaultValue=false)]
        public Dictionary<string, string> BackendMetadata { get; set; }

        /// <summary>
        /// Application metadata. This is the place where you can store your own tags
        /// </summary>
        /// <value>Application metadata. This is the place where you can store your own tags</value>
        [DataMember(Name="applicationMetadata", EmitDefaultValue=false)]
        public Dictionary<string, string> ApplicationMetadata { get; set; }

        /// <summary>
        /// True if the key is backing a certificate
        /// </summary>
        /// <value>True if the key is backing a certificate</value>
        [DataMember(Name="managed", EmitDefaultValue=false)]
        public bool? Managed { get; set; }

        /// <summary>
        /// Key Id
        /// </summary>
        /// <value>Key Id</value>
        [DataMember(Name="kid", EmitDefaultValue=false)]
        public string Kid { get; private set; }

        /// <summary>
        /// The attributes
        /// </summary>
        /// <value>The attributes</value>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public Attributes Attributes { get; set; }

        /// <summary>
        /// Key URL
        /// </summary>
        /// <value>Key URL</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KeyMetadata {\n");
            sb.Append("  BackendMetadata: ").Append(BackendMetadata).Append("\n");
            sb.Append("  ApplicationMetadata: ").Append(ApplicationMetadata).Append("\n");
            sb.Append("  Managed: ").Append(Managed).Append("\n");
            sb.Append("  Kid: ").Append(Kid).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KeyMetadata);
        }

        /// <summary>
        /// Returns true if KeyMetadata instances are equal
        /// </summary>
        /// <param name="other">Instance of KeyMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KeyMetadata other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BackendMetadata == other.BackendMetadata ||
                    this.BackendMetadata != null &&
                    this.BackendMetadata.SequenceEqual(other.BackendMetadata)
                ) && 
                (
                    this.ApplicationMetadata == other.ApplicationMetadata ||
                    this.ApplicationMetadata != null &&
                    this.ApplicationMetadata.SequenceEqual(other.ApplicationMetadata)
                ) && 
                (
                    this.Managed == other.Managed ||
                    this.Managed != null &&
                    this.Managed.Equals(other.Managed)
                ) && 
                (
                    this.Kid == other.Kid ||
                    this.Kid != null &&
                    this.Kid.Equals(other.Kid)
                ) && 
                (
                    this.Attributes == other.Attributes ||
                    this.Attributes != null &&
                    this.Attributes.Equals(other.Attributes)
                ) && 
                (
                    this.Url == other.Url ||
                    this.Url != null &&
                    this.Url.Equals(other.Url)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BackendMetadata != null)
                    hash = hash * 59 + this.BackendMetadata.GetHashCode();
                if (this.ApplicationMetadata != null)
                    hash = hash * 59 + this.ApplicationMetadata.GetHashCode();
                if (this.Managed != null)
                    hash = hash * 59 + this.Managed.GetHashCode();
                if (this.Kid != null)
                    hash = hash * 59 + this.Kid.GetHashCode();
                if (this.Attributes != null)
                    hash = hash * 59 + this.Attributes.GetHashCode();
                if (this.Url != null)
                    hash = hash * 59 + this.Url.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
