/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Crypto.Keys.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Crypto.Keys.Model
{
    /// <summary>
    /// Properties of the key pair backing the certificate
    /// </summary>
    [DataContract]
    public partial class KeyProperties :  IEquatable<KeyProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyProperties" /> class.
        /// </summary>
        /// <param name="Kty">Key type.</param>
        /// <param name="Exportable">Whether the private key is exportable.</param>
        /// <param name="KeySize">The key size in bytes. eg 1024, 2048 or 4096.</param>
        /// <param name="ReuseOnRenewal">Indicates if the same key pair will be used on certificate renewal.</param>
        public KeyProperties(string Kty = default(string), bool? Exportable = default(bool?), int? KeySize = default(int?), bool? ReuseOnRenewal = default(bool?))
        {
            this.Kty = Kty;
            this.Exportable = Exportable;
            this.KeySize = KeySize;
            this.ReuseOnRenewal = ReuseOnRenewal;
        }
        
        /// <summary>
        /// Key type
        /// </summary>
        /// <value>Key type</value>
        [DataMember(Name="kty", EmitDefaultValue=false)]
        public string Kty { get; set; }

        /// <summary>
        /// Whether the private key is exportable
        /// </summary>
        /// <value>Whether the private key is exportable</value>
        [DataMember(Name="exportable", EmitDefaultValue=false)]
        public bool? Exportable { get; set; }

        /// <summary>
        /// The key size in bytes. eg 1024, 2048 or 4096
        /// </summary>
        /// <value>The key size in bytes. eg 1024, 2048 or 4096</value>
        [DataMember(Name="keySize", EmitDefaultValue=false)]
        public int? KeySize { get; set; }

        /// <summary>
        /// Indicates if the same key pair will be used on certificate renewal
        /// </summary>
        /// <value>Indicates if the same key pair will be used on certificate renewal</value>
        [DataMember(Name="reuseOnRenewal", EmitDefaultValue=false)]
        public bool? ReuseOnRenewal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KeyProperties {\n");
            sb.Append("  Kty: ").Append(Kty).Append("\n");
            sb.Append("  Exportable: ").Append(Exportable).Append("\n");
            sb.Append("  KeySize: ").Append(KeySize).Append("\n");
            sb.Append("  ReuseOnRenewal: ").Append(ReuseOnRenewal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KeyProperties);
        }

        /// <summary>
        /// Returns true if KeyProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of KeyProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KeyProperties other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Kty == other.Kty ||
                    this.Kty != null &&
                    this.Kty.Equals(other.Kty)
                ) && 
                (
                    this.Exportable == other.Exportable ||
                    this.Exportable != null &&
                    this.Exportable.Equals(other.Exportable)
                ) && 
                (
                    this.KeySize == other.KeySize ||
                    this.KeySize != null &&
                    this.KeySize.Equals(other.KeySize)
                ) && 
                (
                    this.ReuseOnRenewal == other.ReuseOnRenewal ||
                    this.ReuseOnRenewal != null &&
                    this.ReuseOnRenewal.Equals(other.ReuseOnRenewal)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Kty != null)
                    hash = hash * 59 + this.Kty.GetHashCode();
                if (this.Exportable != null)
                    hash = hash * 59 + this.Exportable.GetHashCode();
                if (this.KeySize != null)
                    hash = hash * 59 + this.KeySize.GetHashCode();
                if (this.ReuseOnRenewal != null)
                    hash = hash * 59 + this.ReuseOnRenewal.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
