/* 
 * Crypto Keys
 *
 * The Crypto Keys API allows you to import, create and work with symmetric and asymmetric keys and certificates to sign/verify digest values, encrypt/decrypt input, or hash and sign input values. The benefit is that you don't have to store secret keys in your application.  The API has an integration with Azure KeyVault, allowing you to store keys, secrets and certificates in FIPS 140-2 Level 2 validated Hardware Security Modules (HSM). The key will never leave the HSM, making it really secure, especially if you combine it with IP whitelisting      Interactive testing: A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Crypto.Keys.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Crypto.Keys.Model
{
    /// <summary>
    /// The verify request (using the digest and signature). Please note that for assymetric encryption we encourage you to do the verification clientside for best performance
    /// </summary>
    [DataContract]
    public partial class KeyVerifyRequest :  IEquatable<KeyVerifyRequest>, IValidatableObject
    {
        /// <summary>
        /// The algorithm to use for signing the diget
        /// </summary>
        /// <value>The algorithm to use for signing the diget</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AlgEnum
        {
            
            /// <summary>
            /// Enum PS256 for "PS256"
            /// </summary>
            [EnumMember(Value = "PS256")]
            PS256,
            
            /// <summary>
            /// Enum PS384 for "PS384"
            /// </summary>
            [EnumMember(Value = "PS384")]
            PS384,
            
            /// <summary>
            /// Enum PS512 for "PS512"
            /// </summary>
            [EnumMember(Value = "PS512")]
            PS512,
            
            /// <summary>
            /// Enum RS256 for "RS256"
            /// </summary>
            [EnumMember(Value = "RS256")]
            RS256,
            
            /// <summary>
            /// Enum RS384 for "RS384"
            /// </summary>
            [EnumMember(Value = "RS384")]
            RS384,
            
            /// <summary>
            /// Enum RS512 for "RS512"
            /// </summary>
            [EnumMember(Value = "RS512")]
            RS512,
            
            /// <summary>
            /// Enum RSNULL for "RSNULL"
            /// </summary>
            [EnumMember(Value = "RSNULL")]
            RSNULL,
            
            /// <summary>
            /// Enum ES256 for "ES256"
            /// </summary>
            [EnumMember(Value = "ES256")]
            ES256,
            
            /// <summary>
            /// Enum ES384 for "ES384"
            /// </summary>
            [EnumMember(Value = "ES384")]
            ES384,
            
            /// <summary>
            /// Enum ES512 for "ES512"
            /// </summary>
            [EnumMember(Value = "ES512")]
            ES512,
            
            /// <summary>
            /// Enum ECDSA256 for "ECDSA256"
            /// </summary>
            [EnumMember(Value = "ECDSA256")]
            ECDSA256
        }

        /// <summary>
        /// The algorithm to use for signing the diget
        /// </summary>
        /// <value>The algorithm to use for signing the diget</value>
        [DataMember(Name="alg", EmitDefaultValue=false)]
        public AlgEnum? Alg { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyVerifyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KeyVerifyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyVerifyRequest" /> class.
        /// </summary>
        /// <param name="Digest">The digest value. This must be a hash that conforms to the algorithm choosen (required).</param>
        /// <param name="Base64Signature">The signature in base 64 form. Please note that the base 64 xor the HEX signature is mandatory..</param>
        /// <param name="Alg">The algorithm to use for signing the diget (required).</param>
        /// <param name="HexSignature">The signature in HEX form. Please note that the base 64 xor the HEX signature is mandatory..</param>
        public KeyVerifyRequest(byte[] Digest = default(byte[]), byte[] Base64Signature = default(byte[]), AlgEnum? Alg = default(AlgEnum?), string HexSignature = default(string))
        {
            // to ensure "Digest" is required (not null)
            if (Digest == null)
            {
                throw new InvalidDataException("Digest is a required property for KeyVerifyRequest and cannot be null");
            }
            else
            {
                this.Digest = Digest;
            }
            // to ensure "Alg" is required (not null)
            if (Alg == null)
            {
                throw new InvalidDataException("Alg is a required property for KeyVerifyRequest and cannot be null");
            }
            else
            {
                this.Alg = Alg;
            }
            this.Base64Signature = Base64Signature;
            this.HexSignature = HexSignature;
        }
        
        /// <summary>
        /// The digest value. This must be a hash that conforms to the algorithm choosen
        /// </summary>
        /// <value>The digest value. This must be a hash that conforms to the algorithm choosen</value>
        [DataMember(Name="digest", EmitDefaultValue=false)]
        public byte[] Digest { get; set; }

        /// <summary>
        /// The signature in base 64 form. Please note that the base 64 xor the HEX signature is mandatory.
        /// </summary>
        /// <value>The signature in base 64 form. Please note that the base 64 xor the HEX signature is mandatory.</value>
        [DataMember(Name="base64Signature", EmitDefaultValue=false)]
        public byte[] Base64Signature { get; set; }


        /// <summary>
        /// The signature in HEX form. Please note that the base 64 xor the HEX signature is mandatory.
        /// </summary>
        /// <value>The signature in HEX form. Please note that the base 64 xor the HEX signature is mandatory.</value>
        [DataMember(Name="hexSignature", EmitDefaultValue=false)]
        public string HexSignature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KeyVerifyRequest {\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Base64Signature: ").Append(Base64Signature).Append("\n");
            sb.Append("  Alg: ").Append(Alg).Append("\n");
            sb.Append("  HexSignature: ").Append(HexSignature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KeyVerifyRequest);
        }

        /// <summary>
        /// Returns true if KeyVerifyRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of KeyVerifyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KeyVerifyRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Digest == other.Digest ||
                    this.Digest != null &&
                    this.Digest.Equals(other.Digest)
                ) && 
                (
                    this.Base64Signature == other.Base64Signature ||
                    this.Base64Signature != null &&
                    this.Base64Signature.Equals(other.Base64Signature)
                ) && 
                (
                    this.Alg == other.Alg ||
                    this.Alg != null &&
                    this.Alg.Equals(other.Alg)
                ) && 
                (
                    this.HexSignature == other.HexSignature ||
                    this.HexSignature != null &&
                    this.HexSignature.Equals(other.HexSignature)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Digest != null)
                    hash = hash * 59 + this.Digest.GetHashCode();
                if (this.Base64Signature != null)
                    hash = hash * 59 + this.Base64Signature.GetHashCode();
                if (this.Alg != null)
                    hash = hash * 59 + this.Alg.GetHashCode();
                if (this.HexSignature != null)
                    hash = hash * 59 + this.HexSignature.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
